version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: facturacion-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: facturacion
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - facturacion-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facturacion-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/facturacion?authSource=admin
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - facturacion-network
    command: npm run start:dev

networks:
  facturacion-network:
    driver: bridge

volumes:
  mongodb_data: